# Generated by Django 4.2 on 2024-10-16 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Oportunidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aceptados', models.BooleanField(blank=True, default=True, null=True)),
                ('cantidad', models.IntegerField(default=0)),
            ],
        ),
    ]
