# Generated by Django 4.2 on 2024-10-16 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_oportunidades_empezoconno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oportunidades',
            name='empezoConNo',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
